### ISSUE TITLE
Option to allow to ignore failures from PerformanceCenter/Loadrunner output

### ISSUE THREAD

**Issue by Jangor67** [stokpop/lograter#1]
When analysing results from PerformanceCenter / Loadrunner. The statistics include the failures. It would be nice if we can make this configurable. e.g. --ignoreFailures 
![67693675-6241ac00-f9a2-11e9-924e-92eb047be1ef](https://user-images.githubusercontent.com/8797018/67696506-4c82b580-f9a7-11e9-9a45-b978296b3310.png)

**Comment by stokpop** [comment]
In lograter 1.3.1 failure hits are excluded in performance center analysis runs.
This behaviour is that then same as pc/alm analysis.
Number of failures and failure percentage remain the same, the hits column only has the succesfull hits. 
There is a new command option for other analysis as well: -incl-failed-hits or --include-failed-hits-in-analysis. Default is true.

**Comment by stokpop** [comment]
See this remark: https://github.com/stokpop/lograter/commit/e2be2b4a35f8c355ff728154b70d66061b530c33#r35786886

**Comment by stokpop** [comment]
With version 1.3.2 there are two new options:

          -failure-aware
            Be failure aware if possible. Report on failed hits in each
            analysis line. If not set the module defaults are used.

         -include-failed-hits-in-analysis
            Include failed hits in analysis. When false the reported number of
            failures and failure percentage are the same for each counter, but
            the other calculated values such as min, max, tps, averaqe,
            percentiles will not include failed hits. "Default behaviour can
            differ for different modules. Most have true, performance center
            analysis has false.
