### ISSUE TITLE
Lograter does not consider TimeZone offset for Loadrunner Enterprise

### ISSUE THREAD

**Issue by WvdKra** [stokpop/lograter#11]
The TimeZone offset is not taken into account in the below Lograter calculation.
https://github.com/stokpop/lograter/blob/323eede845eb44c6ecbafd375dd754d28fd08169/src/main/java/nl/stokpop/lograter/processor/performancecenter/PerformanceCenterCalculator.java#L82

What is the problem:
If the loadrunner controller/dataprocessor is set to a different timezone then a wrong timezone is being used in the calculation of localStartTimeSecEpoch. This can lead to wrong start and endtimes in Lograter graphs.

Microfocus (nowadays OpenText) provided this information to us.
Timings are taken from the table "Result" from the loadrunner Results_<RunId>.mdb file.
There is a "Time Zone" column and a "Start Time" column.
This "Start Time" looks UTC but it is not according to OpenText.
It is the time in the specific "Time Zone" set on the LRE controller but is not included in the PerformanceCenterCalculator.

**Comment by WvdKra** [comment]
OpenText said about the Start Time:
All the data generated is based on the controller timezone, meaning the time shown there it will be in the UTC+1:00) time.

**Comment by stokpop** [comment]
Released in 1.5.2
