### ISSUE TITLE
NPE when isFailureAware is not set

### ISSUE THREAD

**Issue by Jangor67** [stokpop/lograter#2]
In the **BasicCounterLogConfig** class an Optional.**of**  is used for failureAwareAnalysis this should be an **ofNullable** to make de detection in **LogCounterTextReport** (line 107) work.

**Comment by stokpop** [comment]
No need anymore for null value of this settings, will set default to true and make it a boolean instead of Boolean, completely removing the need for Optional.
Only when explicit command line options are given the defaults per module are overruled.
Fix in upcoming v1.3.3
