### ISSUE TITLE
Option to allow to specify max-unique-counters-threshold

### ISSUE THREAD

**Issue by jangor** [stokpop/lograter#3]
While analysing a performance log file with an incorrect matcher pattern the number of internal counters grows too large (no logging available as to specify how large). This results in a slow processing (more like hours instead of minutes) which cannot be currently be controlled or detected.

The currently existing option --max-no-mapper-count could be made more generic to cover this situation as well as the situations where this is now implemented. The default could be 512 perhaps evaluate this default in the future.

**Comment by stokpop** [comment]
The property is now called "--max-unique-counters". The description from command line options: "Maximum number of unique counters before an overflow counter is used that combines all further counters (named OVERFLOW_COUNTER).

This now puts a limit on all RequestCounterStores (Memory, Database and ExternalSort) by wrapping them in a RequestCounterStoreMaxCounters in the RequestCounterStoreFactory.

The default limit is 512.

See example in nl.stokpop.lograter.run.AccessLogRunTest#testAccessLogOverflow.
That is an access log run with --max-unique-counters 2.

Example output:

    services-mappers-success,hits incl failures,failures,failure%,avg ms,min,max,99% ms,avg TPS,max 
    TPM,avg TPS max TPM,max TPM ts,TPM in overall max TPM,TPS in overall max TPM,overall%
    OVERFLOW-COUNTER,16,8,50.00,113,6,332,332,0.00,8,0.13,20121221T000105,8,0.13,11.11
    ion aal,12,0,0.00,578,237,971,971,0.00,6,0.10,20121221T000103,6,0.10,8.33
    vee fib,50,0,0.00,174,17,882,882,0.01,25,0.42,20121221T000104,25,0.42,34.72

**Comment by stokpop** [comment]
Fix is in LogRater 1.3.3
