### ISSUE TITLE
Need a flag for disregarding filter for measuring response times for controllers (outer naming) in JMeter

### ISSUE THREAD

**Issue by naser-ayat** [stokpop/lograter#8]
Add option to ignore the filter for controllers. The part about "Number of transactions in call" can be ignored as this option is just to measure that one controller separately for the number it passed or failed and the response times measured for the entire controller (in case of multiple HTTP hits belonging to one user transaction)

Default behaviour should stay unchanged.
Preferred an additional flag to disable hits filter, or enable full response time reporting, something of that kind.

**Comment by stokpop** [comment]
The jmeter report has an additional flag now (version 1.4.3):

```text
--report-logline-type sample 
The logline type to use in the report. Choose: sample, transaction, all. Default: sample (e.g. http requests)
```

Can also be called via API:

```java
JMeterConfig config = new JMeterConfig();
...
config.setLogLineTypeToReport(JMeterLogLineType.SAMPLE)
```

Each line in the jMeter jtl report is classified as sampler sample (e.g. http request) or controller transaction.

Seems jMeter sometimes reports transaction controller sample lines without the marker in the responseMessage column: "Number of samples in transaction". So also in the jMeter's own report these are reported as regular samples, which seems incorrect

LogRater looks at URL column if present and uses that in favour of the responseMessage check
if the URL is not there, the responseMessage filter is used (so the controller transactions are reported
as "regular" samples).

When controller and sampler names are the same, they are reported in the same counter. This is also what jMeter report seems to do. 

See all edge cases, and probable bug case as described above, in the test cases: https://github.com/stokpop/lograter/blob/master/src/test/java/nl/stokpop/lograter/run/JmeterRunTest.java
